# CRMArena Database Tools Configuration
tools:
  - class_name: verl.tools.gsm8k_tool.Gsm8kTool  # Using existing tool as template for now
    config:
      type: native
      database_type: crmarena
      org_type: original
    tool_schema:
      type: function
      function:
        name: database_query
        description: "IMPORTANT: Always use 'database_query' as the function name. Execute CRM database queries to retrieve and analyze customer data. This is the ONLY valid function name - do not call individual functions directly."
        parameters:
          type: object
          properties:
            function_name:
              type: string
              description: Name of the database function to call
              enum:
                - get_agents_with_max_cases
                - get_agents_with_min_cases
                - calculate_average_handle_time
                - get_start_date
                - get_period
                - get_agent_handled_cases_by_period
                - get_qualified_agent_ids_by_case_count
                - get_cases
                - get_non_transferred_case_ids
                - get_agent_transferred_cases_by_period
                - get_shipping_state
                - calculate_region_average_closure_times
                - get_order_item_ids_by_product
                - get_issue_counts
                - find_id_with_max_value
                - find_id_with_min_value
                - get_account_id_by_contact_id
                - get_purchase_history
                - get_month_to_case_count
                - search_knowledge_articles
                - search_products
                - get_issues
                - get_email_messages_by_case_id
                - get_livechat_transcript_by_case_id
                - submit
            arguments:
              type: object
              description: Arguments for the database function (varies by function)
          required:
            - function_name