# @package _global_

defaults:
  - /ppo_trainer@_here_

# Override defaults for Arc Vision GRPO training
data:
  # Data files will be overridden by command line
  train_files: placeholder
  val_files: placeholder
  
  # Core data configuration
  train_batch_size: 64
  val_batch_size: 32
  max_prompt_length: 1024
  max_response_length: 512
  return_raw_chat: true
  image_key: images
  filter_overlong_prompts: true
  truncation: error
  reward_fn_key: ground_truth

# Custom reward function configuration
custom_reward_function:
  path: placeholder  # Will be overridden by command line
  name: arc_vision_compute_reward

# Disable neural reward model  
reward_model:
  enable: false
  reward_manager: naive